name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        ## no Linux stanza in build-cmd.sh
        os: [windows-2022, macos-11] ##, ubuntu-22.04]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: "64"
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v1
        with:
          public: true
